import type { ScreeningResult } from "./screening";

/**
 * Single source of truth for verdict styling.
 *
 * Five surfaces render verdict pills + scores with semantic color: sidebar row,
 * dashboard card, screening detail header, public share page, and the OG image
 * generated by `next/og` (which runs in a totally different runtime and can't
 * read CSS variables). Hardcoding hex strings in five places guarantees they
 * drift. This module is the one place that knows the mapping; everything else
 * imports from here.
 *
 * The CSS variables in `globals.css` MUST match the `color`, `bg`, and `ring`
 * fields below. The drift test in `verdict-style.test.ts` asserts this; if you
 * change a value here, run `pnpm test` and update `globals.css` to match.
 */

export type Verdict = ScreeningResult["verdict"];

interface VerdictStyle {
  /** Human-readable label, e.g. "Strong match". */
  label: string;
  /** Solid semantic color (text, dot, score numerals). */
  color: string;
  /** 10% alpha tint of `color` (pill background). */
  bg: string;
  /** 30% alpha tint of `color` (pill ring). */
  ring: string;
  /** CSS-variable token name (without the `--`) so consumers in CSS land can map back. */
  cssVar: string;
}

export const verdictStyle: Record<Verdict, VerdictStyle> = {
  strong: {
    label: "Strong match",
    color: "#15803d",
    bg: "#15803d1a",
    ring: "#15803d4d",
    cssVar: "success",
  },
  moderate: {
    label: "Moderate match",
    color: "#2563eb",
    bg: "#2563eb1a",
    ring: "#2563eb4d",
    cssVar: "accent",
  },
  weak: {
    label: "Weak match",
    color: "#b45309",
    bg: "#b453091a",
    ring: "#b453094d",
    cssVar: "warning",
  },
  wrong_role: {
    label: "Wrong role",
    color: "#b91c1c",
    bg: "#b91c1c1a",
    ring: "#b91c1c4d",
    cssVar: "danger",
  },
};

/** Convenience accessor that never returns undefined for a known Verdict. */
export function styleFor(verdict: Verdict): VerdictStyle {
  return verdictStyle[verdict];
}
