import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import { getScreeningForShare } from "@/lib/db/repositories";
import { VerdictHeader } from "@/components/verdict-header";
import { RequirementList } from "@/components/requirement-list";
import { Recommendation } from "@/components/recommendation";

export const dynamic = "force-dynamic";

interface RouteParams {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({
  params,
}: RouteParams): Promise<Metadata> {
  const { slug } = await params;
  const screening = await getScreeningForShare(slug);
  if (!screening) return { title: "Verdict not found · Workfully" };
  const { candidateName, role, verdict, score, summary } = screening.result;

  const verdictLabel =
    verdict === "wrong_role"
      ? "Wrong role"
      : `${verdict[0]!.toUpperCase()}${verdict.slice(1)} match`;

  return {
    title: `${candidateName} · ${verdictLabel} · Workfully`,
    description: `${score}/100 · ${summary.slice(0, 160)}`,
    openGraph: {
      title: `${candidateName} · ${verdictLabel}`,
      description: `${score}/100 · ${role}`,
      images: [
        {
          url: `/s/${slug}/opengraph-image`,
          width: 1200,
          height: 630,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${candidateName} · ${verdictLabel}`,
      description: `${score}/100 · ${role}`,
      images: [`/s/${slug}/opengraph-image`],
    },
  };
}

export default async function PublicShare({ params }: RouteParams) {
  const { slug } = await params;
  const screening = await getScreeningForShare(slug);
  if (!screening) notFound();

  return (
    <main className="mx-auto w-full max-w-[720px] px-6 pt-12 pb-20">
      <header className="mb-8 flex items-center gap-2 text-[15px] font-bold tracking-tight">
        <span aria-hidden className="bg-accent size-2 rounded-[2px]" />
        Workfully
      </header>

      <VerdictHeader
        result={screening.result}
        meta={{
          model: screening.model,
          latencyMs: screening.latencyMs,
          createdAt: screening.createdAt,
        }}
      />

      <RequirementList title="Must-haves" items={screening.result.mustHaves} />
      <RequirementList
        title="Nice-to-haves"
        items={screening.result.niceToHaves}
      />

      <Recommendation text={screening.result.recommendation} readOnly />

      <footer className="border-border text-fg-subtle mt-12 flex items-center justify-between border-t pt-6 text-[12px]">
        <span>Generated by Workfully</span>
        <Link href="/" className="text-fg-muted font-mono hover:underline">
          workfully.app
        </Link>
      </footer>
    </main>
  );
}
