import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getScreeningForShare } from "@/lib/db/repositories";
import { Pill } from "@/components/ui/pill";
import { ScoreDisplay } from "@/components/ui/score-display";
import { RequirementList } from "@/components/requirement-list";
import { Recommendation } from "@/components/recommendation";
import { styleFor, type Verdict } from "@/lib/domain/verdict-style";

export const dynamic = "force-dynamic";

const SUMMARY_BORDER_CLASSES: Record<Verdict, string> = {
  strong: "border-l-success",
  moderate: "border-l-accent",
  weak: "border-l-warning",
  wrong_role: "border-l-danger",
};

interface RouteParams {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({
  params,
}: RouteParams): Promise<Metadata> {
  const { slug } = await params;
  const screening = await getScreeningForShare(slug);
  if (!screening) return { title: "Verdict not found · Workfully" };
  return {
    title: `${screening.result.candidateName} — Workfully verdict`,
  };
}

/**
 * Print-optimized HTML for the share verdict. This is the source of truth
 * that the server-side Chromium PDF route (`./download/route.ts`) navigates
 * to and screenshots as a PDF.
 *
 * Users can also visit this URL directly and use the browser's "Save as PDF"
 * via the print dialog (Cmd+P). The visual output is identical to the
 * server-rendered PDF download.
 */
export default async function ScreeningPdf({ params }: RouteParams) {
  const { slug } = await params;
  const screening = await getScreeningForShare(slug);
  if (!screening) notFound();

  const { result } = screening;
  const s = styleFor(result.verdict);
  const matched = result.mustHaves.filter((m) => m.matched).length;
  const total = result.mustHaves.length;

  return (
    <main className="print-page mx-auto w-full max-w-[720px] px-8 pt-10 pb-12">
      <header className="border-border mb-8 flex items-center justify-between border-b pb-4">
        <div className="flex items-center gap-2 text-[15px] font-bold tracking-tight">
          <span aria-hidden className="bg-accent size-2 rounded-[2px]" />
          Workfully · Screening verdict
        </div>
        <div className="text-fg-subtle font-mono text-[11px]">/s/{slug}</div>
      </header>

      <div className="mb-6 grid grid-cols-[1fr_auto] items-start gap-6">
        <div>
          <div className="mb-3">
            <Pill
              verdict={result.verdict}
              label={`${s.label}${total > 0 ? ` · ${matched} / ${total} must-haves` : ""}`}
            />
          </div>
          <h1 className="text-[22px] leading-tight font-semibold tracking-tight">
            {result.candidateName}
          </h1>
          <div className="text-fg-muted mt-1 text-[14px]">{result.role}</div>
        </div>
        <div className="text-right">
          <div className="text-fg-subtle text-[11px] font-medium tracking-[0.06em] uppercase">
            Fit score
          </div>
          <div className="mt-1">
            <ScoreDisplay
              value={result.score}
              verdict={result.verdict}
              size="lg"
            />
          </div>
        </div>
      </div>

      <p
        className={`mb-8 border-l-2 pl-4 text-[14px] leading-relaxed ${SUMMARY_BORDER_CLASSES[result.verdict]}`}
      >
        {result.summary}
      </p>

      <RequirementList title="Must-haves" items={result.mustHaves} />
      <RequirementList title="Nice-to-haves" items={result.niceToHaves} />

      <Recommendation text={result.recommendation} readOnly />

      <footer className="border-border text-fg-subtle mt-12 flex items-center justify-between border-t pt-4 text-[11px]">
        <span>
          Generated by Workfully · {screening.model} ·{" "}
          {(screening.latencyMs / 1000).toFixed(1)}s
        </span>
        <span className="font-mono">workfully.app/s/{slug}</span>
      </footer>
    </main>
  );
}
